/* Automatically generated by './build/bin/build-entry.js' */

import Dialog from '../packages/dialog/index.js';
import Bubble from '../packages/bubble/index.js';
import Renderless from '../packages/renderless/index.js';

const components = [
  Dialog,
  Bubble,
  Renderless
];

const install = function(Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.812',
  install,
  Dialog,
  Bubble,
  Renderless
};
